fix

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -73,7 +73,16 @@ if [ ! -f $CACHE_FILE ]; then
   IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
 
   echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
-  curl -L --silent $IMAGE_MAGICK_URL | tar xz
+  wget $IMAGE_MAGICK_URL -P $BUILD_DIR
+
+  echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
+    if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
+      echo "Error: Unable to download ImageMagick" | indent
+      ls $BUILD_DIR | indent
+      exit 1;
+    fi
+
+  tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE
 
   echo "-----> Building ImageMagick"
   cd $IMAGE_MAGICK_DIR
